all :
	g++ -std=c++11 NON_BLOCKING_ACCESS.cpp -o exec2
	g++ -std=c++11 STANDARD_DRAM.cpp -o exec
nba : 
	g++ -std=c++11 NON_BLOCKING_ACCESS.cpp -o exec2
dram : 
	g++ -std=c++11 STANDARD_DRAM.cpp -o exec